[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd app && npm install"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["npm start"] 