[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 30

[env]
NODE_ENV = "production"
PORT = "3002"
NODE_OPTIONS = "--max-old-space-size=512" 