[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.start]
cmds = ["npm start"]

[phases.healthcheck]
interval = "30s"
timeout = "10s"
retries = 3

[env]
NODE_ENV = "production" 