[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 600

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --production"]

[phases.start]
cmds = ["node server.js"]

[phases.healthcheck]
interval = 60
timeout = 600
retries = 5
startPeriod = 30

[env]
NODE_ENV = "production"
PORT = "3000"
NODE_OPTIONS = "--max-old-space-size=512" 